"""add table order_items

Revision ID: 842c5c2b49bf
Revises: de0ee6a194aa
Create Date: 2026-01-15 20:46:20.267392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842c5c2b49bf'
down_revision: Union[str, Sequence[str], None] = 'de0ee6a194aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('order_items')
    # ### end Alembic commands ###
