"""create orders table

Revision ID: de0ee6a194aa
Revises: 
Create Date: 2025-08-29 20:24:08.673137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0ee6a194aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'CONFIRMED', 'PAYMENT_FAILED', 'OUT_OF_STOCK',
                                                'PREPARING', 'SHIPPING', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED',
                                                'COMPLETED', 'CANCELLED', 'FAILED', 'REFUNDED', name='orderstatus'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')

    op.execute("""
        DO $$ 
        BEGIN
            -- Проверяем, что тип больше не используется ни в одной таблице
            IF NOT EXISTS (
                SELECT 1 FROM pg_catalog.pg_type t 
                JOIN pg_catalog.pg_enum e ON e.enumtypid = t.oid 
                JOIN pg_catalog.pg_class c ON c.relnamespace = t.typnamespace 
                JOIN pg_catalog.pg_attribute a ON a.atttypid = t.oid AND a.attrelid = c.oid 
                WHERE t.typname = 'orderstatus'
            ) THEN
                DROP TYPE orderstatus;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###
